
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 14 14:27:00 CST 2016
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int dirdir = 25;
  public static final int fsucursal = 58;
  public static final int icor = 7;
  public static final int menor = 66;
  public static final int nomnom = 23;
  public static final int itienda = 41;
  public static final int femail = 38;
  public static final int ptn = 70;
  public static final int punto = 3;
  public static final int iproducto = 59;
  public static final int illave = 74;
  public static final int iid = 17;
  public static final int fimg = 48;
  public static final int fcolor = 54;
  public static final int imarca = 51;
  public static final int fapellido = 34;
  public static final int iimg = 47;
  public static final int fmate = 10;
  public static final int fid = 18;
  public static final int mas = 65;
  public static final int fdireccion = 40;
  public static final int fcrearusuario = 30;
  public static final int inombre = 31;
  public static final int fcantidad = 50;
  public static final int teltel = 24;
  public static final int iusuario = 15;
  public static final int frequest = 14;
  public static final int dolar = 2;
  public static final int cantcant = 27;
  public static final int fcodigo = 44;
  public static final int fpass = 20;
  public static final int ipropietario = 45;
  public static final int sucursucur = 26;
  public static final int id = 62;
  public static final int ftelefono = 36;
  public static final int isucursal = 57;
  public static final int codcod = 22;
  public static final int ptcoma = 12;
  public static final int propipropi = 28;
  public static final int iemail = 37;
  public static final int iapellido = 33;
  public static final int icrearusuario = 29;
  public static final int ftienda = 42;
  public static final int cadenastring = 63;
  public static final int icolor = 53;
  public static final int division = 68;
  public static final int EOF = 0;
  public static final int fllave = 75;
  public static final int cons = 11;
  public static final int imate = 9;
  public static final int fpropietario = 46;
  public static final int apar = 71;
  public static final int numero = 61;
  public static final int ftam = 56;
  public static final int arroba = 4;
  public static final int comillas = 5;
  public static final int cpar = 72;
  public static final int fmarca = 52;
  public static final int icantidad = 49;
  public static final int error = 1;
  public static final int fproducto = 60;
  public static final int irequest = 13;
  public static final int itam = 55;
  public static final int fnombre = 32;
  public static final int ipass = 19;
  public static final int icodigo = 43;
  public static final int por = 67;
  public static final int coma = 73;
  public static final int rq = 69;
  public static final int idireccion = 39;
  public static final int igual = 6;
  public static final int correo = 64;
  public static final int itelefono = 35;
  public static final int fcor = 8;
  public static final int fusuario = 16;
  public static final int tiptip = 21;
}

